version: 0.2

phases:
  install:
    commands: []
  pre_build:
    commands: []
  build:
    commands:
      - >
        date "+%Y%m%d-%H%M%S-$(git rev-parse --short HEAD)"
        > eb-app-version.txt
      - cat eb-app-version.txt
  post_build:
    commands: []
